config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper do
    controllers applications: 'oauth/applications'
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :comments, only: [:create, :destroy]
      resources :users, only: [] do
        collection do
          get 'details'
          get 'inbox'
        end
      end
      resources :posts, only: [:show] do
        collection do
          get 'all'
          get 'my'
          post 'create'
        end
        member do
          post 'upvote'
          post 'downvote'
        end
      end
      resources :subphezes, only: [] do
        collection do
          get 'top'
          get ':path/all' => 'subphezes#all'
          get ':path/latest' => 'subphezes#latest'
          post ':path/subscribe' => 'subphezes#subscribe'
          post ':path/unsubscribe' => 'subphezes#unsubscribe'
        end
      end
      resources :profiles, only: [] do
        collection do
          get ':username/details' => 'profiles#show'
          get ':username/posts' => 'profiles#posts'
          get ':username/comments' => 'profiles#comments'
        end
      end
    end
  end

  resources :newsletters, only: [:new, :create] do
    member do
      get 'confirm'
      get 'unsubscribe'
    end
  end

  resources :admin, only: [:index] do
    collection do
      get 'users'
      get 'payments_csv'
      get 'microtip_csv'
      get 'transactions'
      post 'create_transaction'
      post 'generate_payment_transactions'
    end
    member do
      patch 'freeze'
      patch 'unfreeze'
      patch 'make_ineligible'
      patch 'make_eligible'
    end
  end

  resources :search, only: [:index]

  resources :rewards, only: [:new, :create] do
    collection do
      get 'premium'
      post 'create_rewardable'
    end
    member do
      get 'thanks'
    end
  end
  resources :credits, only: [] do
    collection do
      get 'leaderboard'
      get 'transactions'
      post 'create_transactions'
    end
  end
  resources :subscriptions, only: [:create, :destroy]
  resources :comments, only: [:show, :create, :edit, :update, :destroy]
  resources :posts, except: [:index, :new] do
    collection do
      get 'suggest_title'
    end
  end
  resources :messages, only: [:index, :new, :create]
  resources :profiles, only: [:show] do
    member do
      get 'comments'
    end
  end

  resources :users, only: [] do
    collection do
      get 'subscriptions'
      get 'change_password'
      patch 'update_password'
    end
  end

  resources :home, only: [:index] do
    collection do
      get 'privacy'
      get 'thanks'
      get 'apidocs'
    end
  end

  get 'p/:path' => 'subphezes#show', as: :view_subphez
  get 'p/:path/latest' => 'subphezes#latest', as: :subphez_latest
  get 'p/:path/manage' => 'subphezes#manage', as: :manage_subphez
  post 'p/:path/add_moderator' => 'subphezes#add_moderator', as: :add_moderator_subphez
  post 'p/:path/remove_moderator' => 'subphezes#remove_moderator', as: :remove_moderator_subphez
  get 'p/:path/approve_modrequest' => 'subphezes#approve_modrequest', as: :approve_modrequest
  post 'p/:path/update_modrequest' => 'subphezes#update_modrequest', as: :update_modrequest
  get 'p/:path/submit' => 'posts#new', as: :new_subphez_post
  get 'p/:path/:post_id/:guid/' => 'posts#show', as: :view_post

  get 'submit' => 'posts#new', as: :new_post

  get 'random' => 'subphezes#random', as: :random_subphez

  post 'votes/upvote' => 'votes#upvote'
  post 'votes/downvote' => 'votes#downvote'
  post 'votes/delete_vote' => 'votes#delete_vote'

  post 'comment_votes/upvote' => 'comment_votes#upvote'
  post 'comment_votes/downvote' => 'comment_votes#downvote'

  resources :subphezes, except: [:destroy] do
    collection do
      get 'autocomplete'
    end
  end
  devise_for :users, controllers: { registrations: 'registrations' }

  get 'my' => 'home#my', as: :my
  get 'latest' => 'home#latest', as: :latest
  root 'home#index'

end

app/views/admin/_menu.html.erb
<div class="well admin-heading-well">
  <%= link_to 'Admin Home', admin_index_path %> &nbsp;|&nbsp;
  <%= link_to 'Users', users_admin_index_path %> &nbsp;|&nbsp;
  <%= link_to 'Generate Monthly Transactions', transactions_credits_path %> &nbsp;|&nbsp;
  <%= link_to 'Transactions', transactions_admin_index_path %> &nbsp;|&nbsp;
  <%= link_to 'Payments CSV', payments_csv_admin_index_path %> &nbsp;|&nbsp;
  <%= link_to 'Generate Payment Transactions', generate_payment_transactions_admin_index_path, method: :post, data: { confirm: 'Are you sure?' } %> &nbsp;|&nbsp;
  <%= link_to 'Microtip CSV', microtip_csv_admin_index_path %>
</div>

app/views/admin/index.html.erb
<% title('Admin Dashboard') %>

<%= render :partial => 'menu' %>

<div class="row">

  <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
    <div class="dashboard-panel blue">
      <i class="fa fa-user"></i> <%= @user_count %> Users
    </div>
  </div>

  <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
    <div class="dashboard-panel orangey">
      <i class="fa fa-bookmark"></i> <%= @post_count %> Posts
    </div>
  </div>

  <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
    <div class="dashboard-panel green">
      <i class="fa fa-comments"></i> <%= @comment_count %> Comments
    </div>
  </div>

  <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
    <div class="dashboard-panel red">
      <i class="fa fa-database"></i> <%= @subphez_count %> Subphezes
    </div>
  </div>

</div>

<br/>

<div class="row">

  <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
    <h4>Recent Users</h4>
    <% @users.each do |user| %>
      <div class="spaced-div">
        <%= link_to user.username, build_profile_path(user) %> <%= time_ago_in_words(user.created_at) %> ago
      </div>
    <% end %>
  </div>

  <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
    <h4>Recent Comments</h4>
    <% @comments.each do |comment| %>
      <% @comment = comment %>
      <%= render :partial => 'posts/comment_stripped' %>
    <% end %>
  </div>

</div>

app/views/admin/microtip_csv.html.erb
<%- @users.each do |user| %>
<%= user.bitcoin_address.strip %>,<%= @microtip %><br/>
<% end %>

app/views/admin/payments_csv.html.erb
<%- @payable.each do |user| %>
<%= user.bitcoin_address.strip %>,<%= user.balance.to_i %><br/>
<% end %>

app/views/admin/transactions.html.erb
<% title('Transactions :: Admin') %>

<h2>New Transaction</h2>

<%= form_for(@transaction, url: create_transaction_admin_index_path) do |f| %>
  <% @object = @transaction %>
  <%= render :partial => 'shared/errors' %>

  <div class="field">
    <label>Username</label><br>
    <input type="text" name="username" required="required">
  </div>
  <div class="field">
    <%= f.label :amount_mbtc, "Amount in mBTC" %><br>
    <%= f.text_field :amount_mbtc %>
  </div>
  <div class="field">
    <%= f.label :txn_type, "Transaction Type" %><br/>
    <%= f.select(:txn_type, options_for_select(Transaction.txn_types_for_select), { :include_blank => '(select txn type)'}) %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>

<% end %>


<h2>Transactions</h2>

<table class="transactions-table" style="width: 98%">
  <tr>
    <th>User</th>
    <th>Transaction Type</th>
    <th>Amount (mBTC)</th>
    <th>Deposit Address</th>
    <th>Credit/Withdrawal</th>
    <th>When</th>
  </tr>
  <% @transactions.each do |txn| %>
    <tr>
      <td><%= link_to txn.user.username, build_profile_path(txn.user) %></td>
      <td>
        <%= case txn.txn_type
            when 'reward'
              'phez premium reward'
            when 'content'
              'content contributor'
            when 'development'
              'development'
            when 'misc'
              'miscellaneous / other'
            when 'payment'
              'payment'
            else
              'unknown'
            end
        %>
      </td>
      <td><%= txn.amount_mbtc.round(0) %> mBTC</td>
      <td>
        <% if txn.credit? %>
          N/A - internal
        <% else %>
          <%= txn.bitcoin_address %>
        <% end %>
      </td>
      <td><%= txn.credit? ? 'Credit' : 'Withdrawal' %></td>
      <td><%= txn.created_at %></td>
    </tr>
  <% end %>
</table>

app/views/admin/users.html.erb
<% title('Admin :: Users') %>

<%= render :partial => 'menu' %>


<table class="generic-table" style="width: 98%">
  <tr>
    <th>User</th>
    <th>IP</th>
    <th>Frozen?</th>
    <th>Reward Ineligible?</th>
    <th></th>
  </tr>
  <% @users.each do |user| %>
    <tr>
      <td><%= link_to user.username, build_profile_path(user) %></td>
      <td><%= user.current_sign_in_ip.to_s %></td>
      <td><%= user.is_frozen ? 'Yes' : 'No' %></td>
      <td><%= user.is_reward_ineligible ? 'Yes' : 'No' %></td>
      <td>
        <% if user.is_frozen %>
          <%= link_to 'Unfreeze', unfreeze_admin_path(user), method: :patch, class: 'btn btn-success btn-xs' %>
        <% else %>
          <%= link_to 'Freeze', freeze_admin_path(user), method: :patch, class: 'btn btn-danger btn-xs' %>
        <% end %>
        <% if user.is_reward_ineligible %>
          <%= link_to 'Qualify', make_eligible_admin_path(user), method: :patch, class: 'btn btn-success btn-xs' %>
        <% else %>
          <%= link_to 'Disqualify', make_ineligible_admin_path(user), method: :patch, class: 'btn btn-danger btn-xs' %>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

<%= will_paginate @users %>