config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper do
    controllers applications: 'oauth/applications'
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :comments, only: [:create, :destroy]
      resources :users, only: [] do
        collection do
          get 'details'
          get 'inbox'
        end
      end
      resources :posts, only: [:show] do
        collection do
          get 'all'
          get 'my'
          post 'create'
        end
        member do
          post 'upvote'
          post 'downvote'
        end
      end
      resources :subphezes, only: [] do
        collection do
          get 'top'
          get ':path/all' => 'subphezes#all'
          get ':path/latest' => 'subphezes#latest'
          post ':path/subscribe' => 'subphezes#subscribe'
          post ':path/unsubscribe' => 'subphezes#unsubscribe'
        end
      end
      resources :profiles, only: [] do
        collection do
          get ':username/details' => 'profiles#show'
          get ':username/posts' => 'profiles#posts'
          get ':username/comments' => 'profiles#comments'
        end
      end
    end
  end

  resources :newsletters, only: [:new, :create] do
    member do
      get 'confirm'
      get 'unsubscribe'
    end
  end

  resources :admin, only: [:index] do
    collection do
      get 'users'
      get 'payments_csv'
      get 'microtip_csv'
      get 'transactions'
      post 'create_transaction'
      post 'generate_payment_transactions'
    end
    member do
      patch 'freeze'
      patch 'unfreeze'
      patch 'make_ineligible'
      patch 'make_eligible'
    end
  end

  resources :search, only: [:index]

  resources :rewards, only: [:new, :create] do
    collection do
      get 'premium'
      post 'create_rewardable'
    end
    member do
      get 'thanks'
    end
  end
  resources :credits, only: [] do
    collection do
      get 'leaderboard'
      get 'transactions'
      post 'create_transactions'
    end
  end
  resources :subscriptions, only: [:create, :destroy]
  resources :comments, only: [:show, :create, :edit, :update, :destroy]
  resources :posts, except: [:index, :new] do
    collection do
      get 'suggest_title'
    end
  end
  resources :messages, only: [:index, :new, :create]
  resources :profiles, only: [:show] do
    member do
      get 'comments'
    end
  end

  resources :users, only: [] do
    collection do
      get 'subscriptions'
      get 'change_password'
      patch 'update_password'
    end
  end

  resources :home, only: [:index] do
    collection do
      get 'privacy'
      get 'thanks'
      get 'apidocs'
    end
  end

  get 'p/:path' => 'subphezes#show', as: :view_subphez
  get 'p/:path/latest' => 'subphezes#latest', as: :subphez_latest
  get 'p/:path/manage' => 'subphezes#manage', as: :manage_subphez
  post 'p/:path/add_moderator' => 'subphezes#add_moderator', as: :add_moderator_subphez
  post 'p/:path/remove_moderator' => 'subphezes#remove_moderator', as: :remove_moderator_subphez
  get 'p/:path/approve_modrequest' => 'subphezes#approve_modrequest', as: :approve_modrequest
  post 'p/:path/update_modrequest' => 'subphezes#update_modrequest', as: :update_modrequest
  get 'p/:path/submit' => 'posts#new', as: :new_subphez_post
  get 'p/:path/:post_id/:guid/' => 'posts#show', as: :view_post

  get 'submit' => 'posts#new', as: :new_post

  get 'random' => 'subphezes#random', as: :random_subphez

  post 'votes/upvote' => 'votes#upvote'
  post 'votes/downvote' => 'votes#downvote'
  post 'votes/delete_vote' => 'votes#delete_vote'

  post 'comment_votes/upvote' => 'comment_votes#upvote'
  post 'comment_votes/downvote' => 'comment_votes#downvote'

  resources :subphezes, except: [:destroy] do
    collection do
      get 'autocomplete'
    end
  end
  devise_for :users, controllers: { registrations: 'registrations' }

  get 'my' => 'home#my', as: :my
  get 'latest' => 'home#latest', as: :latest
  root 'home#index'

end

app/views/shared/_bitcoin.html.erb
<div class="row">
  <div class="donate-button-wrapper">
    <%= raw(Figaro.env.donate_code) %>
  </div>
  <div class="col-md-7 donate-text">
    Donate Bitcoin: <%= Figaro.env.bitcoin_address %>
  </div>
</div>
<br/>

app/views/shared/_errors.html.erb
<% if @object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@object.errors.count, "error") %> prohibited this <%= @object.class.to_s %> from being saved:</h2>

    <ul>
    <% @object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_sidebar.html.erb
<div class="col-lg-3">
  <div class="well sidebar-nav">
    <h3>Welcome</h3>
    <p>
      Welcome to Phez.co - the free speech platform. Earn Bitcoin when you participate in the Phez community. <%= link_to 'Learn more', leaderboard_credits_path %>.
    </p>
    <ul class="nav nav-list">
        <li><%= link_to 'Top Subphezes', subphezes_path %></li>
        <li><%= link_to 'Leaderboard', leaderboard_credits_path %></li>
        <li><%= link_to 'Random Subphez', random_subphez_path %></li>
      <% if user_signed_in? %>
        <li><%= link_to 'My Subscriptions', subscriptions_users_path %></li>
        <li><%= link_to 'My Account', edit_user_registration_path %></li>
        <li><%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %></li>
      <% else %>
        <li><%= link_to 'Login', new_user_session_path %></li>
        <li><%= link_to 'Sign Up', new_user_registration_path %></li>
      <% end %>
    </ul>
    <%= link_to 'Submit a New Post', new_post_path, class: 'btn btn-warning' %>
    <br/><br/>
    <%= link_to 'Create a New Subphez', new_subphez_path, class: 'btn btn-primary' %>
    <br/><br/>
    <%= link_to 'Buy Phez Premium', new_reward_path, class: 'btn btn-success' %>
  </div><!--/.well -->
</div>

app/views/shared/_subscribe.html.erb
<div class="newsletter-subscribe">
  <div class="row">
    <div class="col-md-12">
      Phez is a crowdsourced collection of the day's hottest stories, images and videos. Subscribe today to get the top ten posts delivered directly to your inbox every Monday, Wednesday and Friday.
    </div>
  </div>
  <div class="row" style="padding-top: 10px;">
    <div class="col-md-12">
      <center>
      <%= form_for(@newsletter_subscriber, url: newsletters_path) do |f| %>
        <%= f.email_field :email, required: true, placeholder: 'your email' %>
        <%= f.submit 'Subscribe', class: 'btn btn-primary' %>
      <% end %>
      </center>
    </div>
  </div>

</div>
<br/>