config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper do
    controllers applications: 'oauth/applications'
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :comments, only: [:create, :destroy]
      resources :users, only: [] do
        collection do
          get 'details'
          get 'inbox'
        end
      end
      resources :posts, only: [:show] do
        collection do
          get 'all'
          get 'my'
          post 'create'
        end
        member do
          post 'upvote'
          post 'downvote'
        end
      end
      resources :subphezes, only: [] do
        collection do
          get 'top'
          get ':path/all' => 'subphezes#all'
          get ':path/latest' => 'subphezes#latest'
          post ':path/subscribe' => 'subphezes#subscribe'
          post ':path/unsubscribe' => 'subphezes#unsubscribe'
        end
      end
      resources :profiles, only: [] do
        collection do
          get ':username/details' => 'profiles#show'
          get ':username/posts' => 'profiles#posts'
          get ':username/comments' => 'profiles#comments'
        end
      end
    end
  end

  resources :newsletters, only: [:new, :create] do
    member do
      get 'confirm'
      get 'unsubscribe'
    end
  end

  resources :admin, only: [:index] do
    collection do
      get 'users'
      get 'payments_csv'
      get 'microtip_csv'
      get 'transactions'
      post 'create_transaction'
      post 'generate_payment_transactions'
    end
    member do
      patch 'freeze'
      patch 'unfreeze'
      patch 'make_ineligible'
      patch 'make_eligible'
    end
  end

  resources :search, only: [:index]

  resources :rewards, only: [:new, :create] do
    collection do
      get 'premium'
      post 'create_rewardable'
    end
    member do
      get 'thanks'
    end
  end
  resources :credits, only: [] do
    collection do
      get 'leaderboard'
      get 'transactions'
      post 'create_transactions'
    end
  end
  resources :subscriptions, only: [:create, :destroy]
  resources :comments, only: [:show, :create, :edit, :update, :destroy]
  resources :posts, except: [:index, :new] do
    collection do
      get 'suggest_title'
    end
  end
  resources :messages, only: [:index, :new, :create]
  resources :profiles, only: [:show] do
    member do
      get 'comments'
    end
  end

  resources :users, only: [] do
    collection do
      get 'subscriptions'
      get 'change_password'
      patch 'update_password'
    end
  end

  resources :home, only: [:index] do
    collection do
      get 'privacy'
      get 'thanks'
      get 'apidocs'
    end
  end

  get 'p/:path' => 'subphezes#show', as: :view_subphez
  get 'p/:path/latest' => 'subphezes#latest', as: :subphez_latest
  get 'p/:path/manage' => 'subphezes#manage', as: :manage_subphez
  post 'p/:path/add_moderator' => 'subphezes#add_moderator', as: :add_moderator_subphez
  post 'p/:path/remove_moderator' => 'subphezes#remove_moderator', as: :remove_moderator_subphez
  get 'p/:path/approve_modrequest' => 'subphezes#approve_modrequest', as: :approve_modrequest
  post 'p/:path/update_modrequest' => 'subphezes#update_modrequest', as: :update_modrequest
  get 'p/:path/submit' => 'posts#new', as: :new_subphez_post
  get 'p/:path/:post_id/:guid/' => 'posts#show', as: :view_post

  get 'submit' => 'posts#new', as: :new_post

  get 'random' => 'subphezes#random', as: :random_subphez

  post 'votes/upvote' => 'votes#upvote'
  post 'votes/downvote' => 'votes#downvote'
  post 'votes/delete_vote' => 'votes#delete_vote'

  post 'comment_votes/upvote' => 'comment_votes#upvote'
  post 'comment_votes/downvote' => 'comment_votes#downvote'

  resources :subphezes, except: [:destroy] do
    collection do
      get 'autocomplete'
    end
  end
  devise_for :users, controllers: { registrations: 'registrations' }

  get 'my' => 'home#my', as: :my
  get 'latest' => 'home#latest', as: :latest
  root 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, only: [:my]

  def index
    to_show_premium = user_signed_in? ? current_user.is_premium : false
    @posts = Post.by_hot_score
             .show_premium(to_show_premium)
             .paginate(page: params[:page])
    @vote_hash = Vote.vote_hash(current_user, @posts)
    @newsletter_subscriber = NewsletterSubscriber.new
  end

  def my
    to_show_premium = user_signed_in? ? current_user.is_premium : false
    @posts = Post.my_phez(current_user, params[:page], to_show_premium)
    @vote_hash = Vote.vote_hash(current_user, @posts)
  end

  def latest
    to_show_premium = user_signed_in? ? current_user.is_premium : false
    @posts = Post.latest
             .show_premium(to_show_premium)
             .paginate(page: params[:page])
    @vote_hash = Vote.vote_hash(current_user, @posts)
  end

  def privacy
  end

  def thanks
  end

  def apidocs
  end
end

app/views/home/index.html.erb
<% title('Home') %>

<% if !user_signed_in? %>
  <%= render partial: 'shared/subscribe' %>
<% end %>

<%= render partial: 'subphezes/recently_created' %>

<br/>

<% if user_signed_in? %>
  <div class="well subphez-heading-well">
    <ul class="list-inline">
      <li><h2>All</h2></li>
      <li>&nbsp;&nbsp;</li>
      <li><h2><%= link_to 'My Phez', my_path %></h2></li>
    </ul>
  </div>
<% end %>

<%= render partial: 'shared/bitcoin' %>

<% @posts.each do |post| %>
  <% @post = post %>
  <%= render :partial => 'posts/heading' %>
<% end %>

<%= will_paginate @posts %>

<% content_for :sidebar do %>
  <%= render partial: 'shared/sidebar' %>
<% end %>

app/views/home/latest.html.erb
<% title('Latest Posts') %>

<% @posts.each do |post| %>
  <% @post = post %>
  <%= render :partial => 'posts/heading' %>
<% end %>

<%= will_paginate @posts %>

<% content_for :sidebar do %>
  <%= render :partial => 'shared/sidebar' %>
<% end %>

app/views/home/my.html.erb
<% title('Home') %>

<%= render :partial => 'subphezes/recently_created' %>

<br/>

<div class="well subphez-heading-well">
  <ul class="list-inline">
    <li><h2><%= link_to 'All', root_path %></h2></li>
    <li>&nbsp;&nbsp;</li>
    <li><h2>My Phez</h2></li>
  </ul>
</div>

<% @posts.each do |post| %>
  <% @post = post %>
  <%= render :partial => 'posts/heading' %>
<% end %>

<%= will_paginate @posts %>

<% content_for :sidebar do %>
  <%= render :partial => 'shared/sidebar' %>
<% end %>

app/views/home/privacy.html.erb
<h2>Privacy Policy</h2>

<p>Instead of some long-winded block of legalese, here is Phez's privacy policy in plain english:</p>

<p>1. We will never rent, sell, share or disclose your private information to anyone, except as required by a law enforcement agency or by judicial ruling in the United States of America.</p>

<p>2. Deleted posts and comments are actually deleted from the database, although some information may remain in our server logs. You may review the source code to the Phez platform on GitHub at: <a href="https://github.com/phezco/phez">https://github.com/phezco/phez</a></p>

<p>3. Phez is still in its infancy. Some features are not available in the user interface yet (such as account deletion), however we will make a best effort to get this implemented quickly and to allow you to control your user data as you see fit.</p>

<p>4. If you disagree with anything in this policy or would like to see it changed, please post in <%= link_to '/p/PhezRequests', '/p/PhezRequests' %> and we will review your request.</p>

<p>Sincerely,</p>

<p>The Phez Team</p>

app/views/home/thanks.html.erb
<% title('Thank you for your donation') %>

<h2>Thank You</h2>

<p>Thank you for your donation. We really appreciate it.</p>

<p>Your support will allow us to continue growing as an online community, dedicated to the principles of free-speech.</p>