config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper do
    controllers applications: 'oauth/applications'
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :comments, only: [:create, :destroy]
      resources :users, only: [] do
        collection do
          get 'details'
          get 'inbox'
        end
      end
      resources :posts, only: [:show] do
        collection do
          get 'all'
          get 'my'
          post 'create'
        end
        member do
          post 'upvote'
          post 'downvote'
        end
      end
      resources :subphezes, only: [] do
        collection do
          get 'top'
          get ':path/all' => 'subphezes#all'
          get ':path/latest' => 'subphezes#latest'
          post ':path/subscribe' => 'subphezes#subscribe'
          post ':path/unsubscribe' => 'subphezes#unsubscribe'
        end
      end
      resources :profiles, only: [] do
        collection do
          get ':username/details' => 'profiles#show'
          get ':username/posts' => 'profiles#posts'
          get ':username/comments' => 'profiles#comments'
        end
      end
    end
  end

  resources :newsletters, only: [:new, :create] do
    member do
      get 'confirm'
      get 'unsubscribe'
    end
  end

  resources :admin, only: [:index] do
    collection do
      get 'users'
      get 'payments_csv'
      get 'microtip_csv'
      get 'transactions'
      post 'create_transaction'
      post 'generate_payment_transactions'
    end
    member do
      patch 'freeze'
      patch 'unfreeze'
      patch 'make_ineligible'
      patch 'make_eligible'
    end
  end

  resources :search, only: [:index]

  resources :rewards, only: [:new, :create] do
    collection do
      get 'premium'
      post 'create_rewardable'
    end
    member do
      get 'thanks'
    end
  end
  resources :credits, only: [] do
    collection do
      get 'leaderboard'
      get 'transactions'
      post 'create_transactions'
    end
  end
  resources :subscriptions, only: [:create, :destroy]
  resources :comments, only: [:show, :create, :edit, :update, :destroy]
  resources :posts, except: [:index, :new] do
    collection do
      get 'suggest_title'
    end
  end
  resources :messages, only: [:index, :new, :create]
  resources :profiles, only: [:show] do
    member do
      get 'comments'
    end
  end

  resources :users, only: [] do
    collection do
      get 'subscriptions'
      get 'change_password'
      patch 'update_password'
    end
  end

  resources :home, only: [:index] do
    collection do
      get 'privacy'
      get 'thanks'
      get 'apidocs'
    end
  end

  get 'p/:path' => 'subphezes#show', as: :view_subphez
  get 'p/:path/latest' => 'subphezes#latest', as: :subphez_latest
  get 'p/:path/manage' => 'subphezes#manage', as: :manage_subphez
  post 'p/:path/add_moderator' => 'subphezes#add_moderator', as: :add_moderator_subphez
  post 'p/:path/remove_moderator' => 'subphezes#remove_moderator', as: :remove_moderator_subphez
  get 'p/:path/approve_modrequest' => 'subphezes#approve_modrequest', as: :approve_modrequest
  post 'p/:path/update_modrequest' => 'subphezes#update_modrequest', as: :update_modrequest
  get 'p/:path/submit' => 'posts#new', as: :new_subphez_post
  get 'p/:path/:post_id/:guid/' => 'posts#show', as: :view_post

  get 'submit' => 'posts#new', as: :new_post

  get 'random' => 'subphezes#random', as: :random_subphez

  post 'votes/upvote' => 'votes#upvote'
  post 'votes/downvote' => 'votes#downvote'
  post 'votes/delete_vote' => 'votes#delete_vote'

  post 'comment_votes/upvote' => 'comment_votes#upvote'
  post 'comment_votes/downvote' => 'comment_votes#downvote'

  resources :subphezes, except: [:destroy] do
    collection do
      get 'autocomplete'
    end
  end
  devise_for :users, controllers: { registrations: 'registrations' }

  get 'my' => 'home#my', as: :my
  get 'latest' => 'home#latest', as: :latest
  root 'home#index'

end

app/models/subphez.rb
class Subphez < ActiveRecord::Base
  validates :path,
            format: { with: /\A[a-zA-Z0-9]+\Z/ },
            length: { minimum: 1, maximum: 30 },
            uniqueness: { case_sensitive: false }
  validates :title, presence: true

  belongs_to :user
  has_many :posts
  has_many :moderations
  has_many :moderators, through: :moderations
  has_many :subscriptions
  has_many :subscribers, through: :subscriptions

  scope :latest, -> { order('created_at DESC') }

  before_save :sanitize_attributes
  after_create :add_owner_as_moderator
  after_create :subscribe_creator

  MaxPerUser = 3

  def url
    "http://#{Figaro.env.app_domain}/p/#{path}"
  end

  def atom_feed
    "#{url}.atom"
  end

  def subscriber_count
    Subscription.where(subphez_id: id).count
  end

  def sidebar_rendered
    return '' if sidebar.blank?
    Renderer.render(sidebar)
  end

  def owner?(the_user)
    the_user.id == user_id
  end

  def can_moderate?(the_user)
    moderators.include?(the_user)
  end

  def add_owner_as_moderator
    Moderation.create!(user_id: user_id, subphez_id: id)
  end

  def add_moderator!(new_moderator)
    Moderation.create!(user_id: new_moderator.id, subphez_id: id)
  end

  def subscribe_creator
    Subscription.subscribe!(self, user)
  end

  def sanitize_attributes
    self.title = Sanitizer.sanitize(title) unless title.blank?
    self.sidebar = Sanitizer.sanitize(sidebar) unless sidebar.blank?
  end

  def self.by_path(path)
    Subphez.where('LOWER(path) = ?', path.downcase).first
  end

  def self.top_by_subscriber_count(limit = 100)
    subphezes = Subphez.all
    subphezes = subphezes.map { |s| s }.sort! { |a, b| b.subscriber_count <=> a.subscriber_count }
    subphezes[0..(limit - 1)]
  end
end

app/controllers/api/v1/subphezes_controller.rb
class Api::V1::SubphezesController < Api::V1::BaseController
  before_action :set_subphez_by_path, except: [:top]
  before_action :doorkeeper_authorize!, only: [:subscribe, :unsubscribe]
  before_action :authenticate_user!, only: [:subscribe, :unsubscribe]

  def top
    @subphezes = Subphez.top_by_subscriber_count(100)
    render json: @subphezes, each_serializer: SubphezSerializer
  end

  def all
    api_disallow_non_premium(@subphez)
    @posts = @subphez.posts.by_hot_score.paginate(page: params[:page])
    render json: @posts, each_serializer: PostSerializer
  end

  def latest
    api_disallow_non_premium(@subphez)
    @posts = @subphez.posts.latest.paginate(page: params[:page])
    render json: @posts, each_serializer: PostSerializer
  end

  def subscribe
    api_disallow_non_premium(@subphez)
    subscription = Subscription.subscribe!(@subphez, current_resource_owner)
    if subscription
      json = { 'success' => true }
      render json: json
    else
      json = { 'success' => false, 'errors' => 'already subscribed' }
      render json: json
    end
  end

  def unsubscribe
    subscription = Subscription.unsubscribe!(@subphez, current_resource_owner)
    if subscription
      json = { 'success' => true }
      render json: json
    else
      json = { 'success' => false, 'errors' => 'not subscribed' }
      render json: json
    end
  end

  private

  def set_subphez_by_path
    @subphez = Subphez.by_path(params[:path])
    if @subphez.nil?
      render(json: errors_json("Could not find subphez: #{params[:path]}"), status: :not_found) and return
    end
  end
end

app/controllers/subphezes_controller.rb
class SubphezesController < ApplicationController
  before_action :authenticate_user!,
                except: [:index, :show, :latest, :autocomplete, :random]
  before_action :set_subphez, only: [:edit, :update, :destroy]
  before_action :set_subphez_by_path,
                only: [:show, :latest, :manage, :add_moderator,
                       :remove_moderator, :approve_modrequest,
                       :update_modrequest]

  before_action :frozen_check!,
                only: [:new, :create, :update, :manage, :approve_moderator,
                       :remove_moderator, :approve_modrequest, :update_modrequest]

  def autocomplete
    @subphezes = Subphez.where('path ILIKE ?', "#{params[:term]}%")
                 .order('path ASC')
    @paths = @subphezes.collect(&:path)
    respond_to do |format|
      format.json { render json: @paths.to_json }
    end
  end

  # GET /subphezs
  # GET /subphezs.json
  def index
    @subphezes = Subphez.top_by_subscriber_count(100)
  end

  # GET /subphezs/1
  # GET /subphezs/1.json
  def show
    disallow_non_premium(@subphez)
    @posts = @subphez.posts.by_hot_score.paginate(page: params[:page])
    @vote_hash = Vote.vote_hash(current_user, @posts)
  end

  def latest
    disallow_non_premium(@subphez)
    @posts = @subphez.posts.latest.paginate(page: params[:page])
    @vote_hash = Vote.vote_hash(current_user, @posts)
  end

  def manage
    unless current_user.can_moderate?(@subphez)
      redirect_to(build_subphez_path(@subphez),
                  alert: 'You are not a moderator of this subphez.') and return
    end
    @mod_request = ModRequest.new
  end

  def add_moderator
    unless current_user.can_moderate?(@subphez)
      redirect_to(:back,
                  alert: 'You are not a moderator of this subphez.') and return
    end
    @user = User.by_username_insensitive(params[:username])
    if @user.nil?
      redirect_to(:back,
                  alert: 'Could not find user with that username.') and return
    end
    @mod_request = ModRequest.new(
      user_id: @user.id,
      inviting_user_id: current_user.id,
      subphez_id: @subphez.id
    )
    if @mod_request.save
      redirect_to manage_subphez_path(path: @subphez.path),
                  notice: 'Moderator request sent.'
    else
      redirect_to manage_subphez_path(path: @subphez.path),
                  alert: 'Could not add moderator at this time.'
    end
  end

  def remove_moderator
    unless current_user.is_owner?(@subphez)
      redirect_to(:back,
                  alert: 'You are not the owner of this subphez.') and return
    end
    @user = User.find(params[:user_id])
    unless @subphez.moderators.include?(@user)
      redirect_to(:back,
                  alert: 'This user is not a moderator of this subphez.') and return
    end
    @moderation = Moderation.where(user_id: @user.id)
                  .where(subphez_id: @subphez.id).first
    @moderation.destroy
    redirect_to manage_subphez_path(path: @subphez.path),
                notice: 'Moderator removed.'
  end

  def approve_modrequest
    @mod_request = ModRequest
                   .where(user_id: current_user.id, subphez_id: @subphez.id)
                   .first
    if @mod_request.nil?
      redirect_to :back,
                  alert: 'Could not find add moderator request.' and return
    end
  end

  def update_modrequest
    @mod_request = ModRequest
                   .where(user_id: current_user.id, subphez_id: @subphez.id)
                   .first
    if @mod_request.nil?
      redirect_to(:back,
                  alert: 'Could not find add moderator request.') and return
    end
    @subphez.add_moderator!(current_user)
    redirect_to manage_subphez_path(path: @subphez.path),
                notice: 'Success! You are now a moderator of this subphez.'
  end

  # GET /subphezs/new
  def new
    @subphez = Subphez.new
    if current_user.max_subphezes_reached?
      redirect_to(root_path,
                  alert: "We're sorry, you have reached the maximum number of Subphezes allowable at this time. Please post content to and moderate your existing Subphezes, and we will consider lifting this limit soon.") and return
    end
  end

  # GET /subphezs/1/edit
  def edit
  end

  # POST /subphezs
  # POST /subphezs.json
  def create
    if current_user.max_subphezes_reached?
      redirect_to(root_path,
                  alert: "We're sorry, you have reached the maximum number of Subphezes allowable at this time. Please post content to and moderate your existing Subphezes, and we will consider lifting this limit soon.") and return
    end
    @subphez = Subphez.new(subphez_params)
    @subphez.user_id = current_user.id
    if @subphez.save
      redirect_to view_subphez_path(path: @subphez.path),
                  notice: 'Subphez was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /subphezs/1
  # PATCH/PUT /subphezs/1.json
  def update
    if @subphez.update(subphez_params)
      redirect_to view_subphez_path(path: @subphez.path),
                  notice: 'Subphez was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /subphezs/1
  # DELETE /subphezs/1.json
  # def destroy
  #   @subphez.destroy
  #   respond_to do |format|
  #     format.html
  #       redirect_to subphezs_url,
  #       notice: 'Subphez was successfully destroyed.'
  #     format.json { head :no_content }
  #   end
  # end

  def random
    random_path = Subphez.pluck(:path).sample
    redirect_to view_subphez_path(path: random_path)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_subphez
    @subphez = Subphez.find(params[:id])
  end

  def set_subphez_by_path
    @subphez = Subphez.by_path(params[:path])

    redirect_to(root_path,
                alert: 'Could not find subphez.') and return if @subphez.nil?
  end

  # Never trust parameters from the scary internet,
  # only allow the white list through.
  def subphez_params
    params.require(:subphez).permit(:path, :title, :sidebar)
  end
end

app/helpers/subphezs_helper.rb
module SubphezsHelper
end

app/views/subphezes/_form.html.erb
<%= form_for(@subphez) do |f| %>
  <% @object = @subphez %>
  <%= render :partial => 'shared/errors' %>
  <% if @subphez.new_record? %>
    <div class="field">
      <%= f.label :path %><br>
      phez.co/p/<%= f.text_field :path %> <br/>
      <small><i>Cannot contain any spaces. Maximum 30 characters. No special characters (alphanumeric only).</i></small>
    </div>
  <% else %>
    <p>Subphez path's are not editable.</p>
  <% end %>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: 'title-field' %>
  </div>
  <div class="field">
    <%= f.label :sidebar, "Sidebar Text" %><br>
    <%= f.text_area :sidebar, class: 'body-field' %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/subphezes/_recently_created.html.erb
<div>
  Recently created Subphezes: &nbsp;&nbsp;
  <% Subphez.latest.limit(7).each do |subphez| %>
    <%= link_to "/p/#{subphez.path}", build_subphez_path(subphez) %> &nbsp;&nbsp;&nbsp;
  <% end %>
</div>

app/views/subphezes/_sidebar.html.erb
<div class="col-lg-3">
  <div class="well sidebar-nav">
    <h3>
      <%= link_to @subphez.title, build_subphez_path(@subphez) %>
    </h3>

    <div class="karma">
      <span class="link-karma">
        <%= @subphez.subscriber_count %>
      </span> &nbsp;subscribers
    </div>
    <br/>
    <% if user_signed_in? and current_user.subscribed_subphezes.include?(@subphez) %>
      <%= link_to 'unsubscribe', subscription_path(0, :subphez_id => @subphez.id), method: :delete, class: 'btn btn-danger' %>
    <% else %>
      <%= link_to 'subscribe', subscriptions_path(subphez_id: @subphez.id), method: :post, class: 'btn btn-success' %>
    <% end %>
    <br/>
    <br/>
    <% if !@subphez.is_admin_only || (user_signed_in? and current_user.is_admin) %>
      <%= link_to 'Submit a new link', new_subphez_post_path(:path => @subphez.path), class: 'btn btn-primary' %>
    <% end %>
    <br/>
    <% if user_signed_in? and current_user.can_moderate?(@subphez) %>
      <br/>
      <%= link_to 'Edit this Subphez', edit_subphez_path(@subphez), class: 'btn btn-primary' %>
      <br/><br/>
      <%= link_to 'Manage this Subphez', manage_subphez_path(:path => @subphez.path), class: 'btn btn-primary' %>
      <br/>
    <% end %>

    <br/>
    <div>
      <%= raw(@subphez.sidebar_rendered) %>
    </div>
    <br/>
    <div>
      <h4>Moderators</h4>
      <% @subphez.moderators.each do |mod| %>
        <%= link_to mod.username, build_profile_path(mod) %> <br/>
      <% end %>
    </div>
    <br/>
    <div>
      <%= link_to 'atom feed', @subphez.atom_feed %>
    </div>
  </div>
</div>

app/views/subphezes/approve_modrequest.html.erb
<h2>Moderator Request: <%= @subphez.title %></h2>

<p>
  You have been invited to become a moderator of <%= link_to "/p/#{@subphez.path}", build_subphez_path(@subphez) %>.
</p>

<%= link_to "Become a Moderator of /p/#{@subphez.path}", update_modrequest_path(:path => @subphez.path), method: :post, data: { confirm: 'Are you sure?' }, class: 'btn btn-success' %>

<br/><br/>

<p>If you do not want to become a moderator of this subphez, you may safely ignore this message.</p>

app/views/subphezes/edit.html.erb
<h1>Editing Subphez</h1>

<%= render 'form' %>

app/views/subphezes/index.html.erb
<% title('Top Subphezes') %>

<h2>Top Subphezes</h2>

<% @subphezes.each do |subphez| %>
  <div class="row margin-bottom-20">
    <% if user_signed_in? %>
      <div class="col-md-2 my-subscriptions-unsubscribe">
        <% if current_user.subscribed_subphezes.include?(subphez) %>
          <%= link_to 'unsubscribe', subscription_path(0, :subphez_id => subphez.id), method: :delete, class: 'btn btn-danger btn-sm' %>
        <% else %>
          <%= link_to 'subscribe', subscriptions_path(subphez_id: subphez.id), method: :post, class: 'btn btn-success' %>
        <% end %>
      </div>
    <% end %>
    <div class="col-md-10">
      <h3><%= link_to subphez.title, build_subphez_path(subphez) %></h3>
      <%= link_to "/p/#{subphez.path}", build_subphez_path(subphez) %> | <%= subphez.subscriber_count %> subscribers
    </div>
  </div>
<% end %>

app/views/subphezes/latest.html.erb
<% title("#{@subphez.title} :: latest") %>

<div class="well subphez-heading-well">
  <ul class="list-inline">
    <li><h2><%= link_to 'Hot', build_subphez_path(@subphez) %></h2></li>
    <li>&nbsp;&nbsp;</li>
    <li><h2>New</h2></li>
  </ul>
</div>

<% @posts.each do |post| %>
  <% @post = post %>
  <%= render :partial => 'posts/heading' %>
<% end %>

<%= will_paginate @posts %>

<% content_for :sidebar do %>
  <%= render :partial => 'sidebar' %>
<% end %>

app/views/subphezes/manage.html.erb
<h2>Manage <%= @subphez.title %></h2>

<h3>Add Moderator</h3>

<%= form_for(@mod_request, :url => add_moderator_subphez_path(:path => @subphez.path)) do |f| %>
  <div class="field">
    <%= label_tag :username %><br>
    <%= text_field_tag :username %>
    <br/><i>Enter the username of the user who you'd like to add as a moderator.</i>
  </div>
  <div class="actions">
    <%= f.submit "Add Moderator", class: 'btn btn-primary' %>
  </div>
<% end %>

<h3>Moderators</h3>

<% @subphez.moderators.each do |user| %>
  <%= user.username %>
  <% if current_user.is_owner?(@subphez) and user != current_user %>
    <%= link_to 'Remove Moderator', remove_moderator_subphez_path(:id => @subphez.id, :user_id => user.id), method: :post, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
  <% end %>
  <br/>
<% end %>

<% content_for :sidebar do %>
  <%= render :partial => 'sidebar' %>
<% end %>

app/views/subphezes/new.html.erb
<h1>New Subphez</h1>

<%= render 'form' %>

app/views/subphezes/show.html.erb
<% title("#{@subphez.title} :: hot") %>
<%= content_for :head, auto_discovery_link_tag(:atom, @subphez.atom_feed) %>

<div class="well subphez-heading-well">
  <ul class="list-inline">
    <li><h2>Hot</h2></li>
    <li>&nbsp;&nbsp;</li>
    <li>
      <h2>
        <%= link_to 'New', subphez_latest_path(path: @subphez.path) %>
      </h2>
    </li>
  </ul>
</div>

<% @posts.each do |post| %>
  <% @post = post %>
  <%= render partial: 'posts/heading' %>
<% end %>

<%= will_paginate @posts %>

<% content_for :sidebar do %>
  <%= render partial: 'sidebar' %>
<% end %>